# eda/rulebook.yml
- name: Oracle DRP Event Rulebook
  hosts: localhost
  sources:
    - name: splunk
      ansible.eda.webhook:
        port: 5001
        token: your-splunk-token
    - name: dynatrace
      ansible.eda.webhook:
        port: 5002
        token: your-dynatrace-token
  rules:
    - name: Promote Standby from Splunk
      condition: event.payload.source == "splunk" and event.payload.type == "host_down"
      actions:
        - run_job_template:
            name: Promote Oracle Standby
            organization: Default

    - name: Promote Standby from Dynatrace
      condition: event.payload.source == "dynatrace" and "Primary DB Host Down" in event.payload.title
      actions:
        - run_job_template:
            name: Promote Oracle Standby
            organization: Default
